### ISSUE TITLE
[Level Controls] Digraphs Support

### ISSUE THREAD

**Issue by cKellyDesign** [cKellyDesign/BusyBeeSpelling#11]
This should be pretty easy, should just need to add an array of digraphs to level legends and generate wrong answers.
- [x] Add array to level legend
- [x] Make sure array is searchable with current setup
- [x] Add function to generate random letter pairings for wrong answers for this level
- [x] random letters should not duplicate correct answers (possible?). I noticed on the vowels example there were two "E"s

**Comment by HaYesSeattle** [comment]
[] random letters should not duplicate correct answers  (possible?). I noticed on the vowels example there were two "E"s

**Comment by cKellyDesign** [comment]
Ooh yes! Good call!

**Comment by cKellyDesign** [comment]
@dooderlani - Beth, so I added some functionality to force unique letters and digraphs and it's working pretty well but has some spotty performance with digraphs for some reason. I'm going to keep looking into it, i've only noticed with digraphs and only with "th" and only sometimes which is weird! If you notice any other repeating letters call them out and maybe i can figure this out! :)

**Comment by HaYesSeattle** [comment]
@cKellyDesign - i was just working with vowels and see that there is some dup correct answers...
<img width="581" alt="screen shot 2015-07-28 at 9 42 32 pm" src="https://cloud.githubusercontent.com/assets/3664500/8950100/acb85850-3571-11e5-988b-80ef04c7e179.png">

**Comment by cKellyDesign** [comment]
Ack! My indexOf() logic was off and was allowing the **first** answer in the array to be duplicated! O_o

Fixed with PR #24
