### ISSUE TITLE
[Level] Add Level Complete Functionality

### ISSUE THREAD

**Issue by cKellyDesign** [cKellyDesign/BusyBeeSpelling#12]
When a user gets `x` amount of points or 3(?) strikes the level needs to complete, resulting in a win or lose feedback.
- [x] Points Functionality
- [x] Strikes Functionality
- [x] Level Complete / Fail Panel with `Replay Level` and `Back to Menu` buttons
- [x] Refresh Level Functionality
- [ ] Message Verbiage

**Comment by HaYesSeattle** [comment]
this is a great thing to track! for this age group in the (US society) we don't want a fail panel - they should keep playing until they get it right. But tracking how many times it takes them might be cool - we could potentially use that knowledge to make it harder or move them on to a more advanced reading level based on the fail rate.
(see the flow doc)...I just created some pngs so you don't have to open the illustrator file - I should have done that earlier, sorry about that.

**Comment by cKellyDesign** [comment]
Just checked functionality to have visual feedback when collecting a correct answer in the form of a panel with some rough verbiage, maybe we can sync on what it should say or you can take a wack at it too!

Right now if you click on a wrong answer the letter just disappears and it seems like there should be a bit more feedback that something actually happened. Maybe like making busyBee shake a bit or something?
