### ISSUE TITLE
[Level] In Level Menu Setup

### ISSUE THREAD

**Issue by cKellyDesign** [cKellyDesign/BusyBeeSpelling#13]
There needs to be an in level menu for the user to adjust options and have the option to return to the level select landing screen.
- [x] Graphics @dooderlani 
- [x] Open / Close @ckellydesign
- [x] Include Menu Option buttons @dooderlani 
- [x] Hook up Menu Option functionalities @ckellydesign 
- [x] Menu style finalization (initial styles are rough to get it opening / closing!) @dooderlani 

@dooderlani - Let's trade these tickets back and forth! :smile:

**Comment by HaYesSeattle** [comment]
this seems done
